# Server Port
server.port=8080

# ===============================================
# Database Configuration (PostgreSQL in Prod / H2 fallback in Dev)
# ===============================================
spring.datasource.url=${DB_URL:jdbc:h2:mem:rankquest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# ===============================================
# JPA / Hibernate Configuration
# ===============================================
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console in dev
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console